-- MySQL Script generated by MySQL Workbench
-- 08/22/16 16:49:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema resort_reservation_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema resort_reservation_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `resort_reservation_system` DEFAULT CHARACTER SET utf8 ;
USE `resort_reservation_system` ;

-- -----------------------------------------------------
-- Table `resort_reservation_system`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `contact_number` VARCHAR(15) NULL,
  `address` VARCHAR(50) NULL,
  `birthday` DATE NULL,
  `email` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`manager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin_id` INT NULL,
  `username` VARCHAR(50) NULL,
  `access_date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`regular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`regular` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `salary` DECIMAL(2) NULL,
  `status` VARCHAR(50) NULL,
  `classification` VARCHAR(45) NULL,
  `nature_of_service` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `contact_number` VARCHAR(15) NULL,
  `rate` VARCHAR(20) NULL,
  `hired_date` DATE NULL,
  `department` VARCHAR(50) NULL,
  `type` VARCHAR(45) NULL,
  `position` VARCHAR(50) NULL,
  `email` VARCHAR(50) NULL,
  `address` VARCHAR(50) NULL,
  `birthday` DATE NULL,
  `manager_id` INT NOT NULL,
  `regular_id` INT NOT NULL,
  PRIMARY KEY (`id`, `manager_id`, `regular_id`),
  INDEX `fk_employee_manager1_idx` (`manager_id` ASC),
  INDEX `fk_employee_regular1_idx` (`regular_id` ASC),
  CONSTRAINT `fk_employee_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `resort_reservation_system`.`manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_regular1`
    FOREIGN KEY (`regular_id`)
    REFERENCES `resort_reservation_system`.`regular` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`billingstatement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`billingstatement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mode_of_payment` VARCHAR(20) NULL,
  `amount` DECIMAL(2) NULL,
  `number` INT NULL,
  `date` DATE NULL,
  `status` VARCHAR(45) NULL,
  `employee_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_billing statement_employee1_idx` (`employee_id` ASC),
  INDEX `fk_billing statement_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_billing statement_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `resort_reservation_system`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_billing statement_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `resort_reservation_system`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(50) NULL,
  `type` VARCHAR(45) NULL,
  `rate` VARCHAR(20) NULL,
  `capacity` INT NULL,
  `availability` VARCHAR(45) NULL,
  `billing statement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_room_billing statement1_idx` (`billing statement_id` ASC),
  CONSTRAINT `fk_room_billing statement1`
    FOREIGN KEY (`billing statement_id`)
    REFERENCES `resort_reservation_system`.`billingstatement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`online`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`online` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `actual_access_date` DATE NULL,
  `actual_reserve_date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`walkin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`walkin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `actual_time_in` DATE NULL,
  `actual_time_reserve` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_reserved` DATE NULL,
  `number_of_days` INT NULL,
  `down_payment` VARCHAR(30) NULL,
  `receipt_number` VARCHAR(30) NULL,
  `online_id` INT NOT NULL,
  `walk-in_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_online1_idx` (`online_id` ASC),
  INDEX `fk_reservation_walk-in1_idx` (`walk-in_id` ASC),
  CONSTRAINT `fk_reservation_online1`
    FOREIGN KEY (`online_id`)
    REFERENCES `resort_reservation_system`.`online` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_walk-in1`
    FOREIGN KEY (`walk-in_id`)
    REFERENCES `resort_reservation_system`.`walkin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  `cost` VARCHAR(45) NULL,
  `service_offered` VARCHAR(45) NULL,
  `type_of_service` VARCHAR(45) NULL,
  `employee_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `billing statement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_service_employee1_idx` (`employee_id` ASC),
  INDEX `fk_service_customer1_idx` (`customer_id` ASC),
  INDEX `fk_service_billing statement1_idx` (`billing statement_id` ASC),
  CONSTRAINT `fk_service_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `resort_reservation_system`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `resort_reservation_system`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_billing statement1`
    FOREIGN KEY (`billing statement_id`)
    REFERENCES `resort_reservation_system`.`billingstatement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`customer_has_reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`customer_has_reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_of_arrival` DATE NULL,
  `date_of_departure` DATE NULL,
  `desired_room_type` VARCHAR(20) NULL,
  `required_number_of_rooms` INT NULL,
  `requests` VARCHAR(50) NULL,
  `reservation_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_has_reservation_reservation1_idx` (`reservation_id` ASC),
  INDEX `fk_customer_has_reservation_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_customer_has_reservation_reservation1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `resort_reservation_system`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_has_reservation_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `resort_reservation_system`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`reservation_has_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`reservation_has_room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reservation_start_date` DATE NULL,
  `reservation_end_date` DATE NULL,
  `reservation_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_has_room_reservation1_idx` (`reservation_id` ASC),
  INDEX `fk_reservation_has_room_room1_idx` (`room_id` ASC),
  CONSTRAINT `fk_reservation_has_room_reservation1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `resort_reservation_system`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_has_room_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `resort_reservation_system`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`employee_assist_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`employee_assist_customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_assist_customer_customer1_idx` (`customer_id` ASC),
  INDEX `fk_employee_assist_customer_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_employee_assist_customer_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `resort_reservation_system`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_assist_customer_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `resort_reservation_system`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
