-- MySQL Script generated by MySQL Workbench
-- 12/13/16 19:37:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema resort_reservation_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema resort_reservation_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `resort_reservation_system` DEFAULT CHARACTER SET utf8 ;
USE `resort_reservation_system` ;

-- -----------------------------------------------------
-- Table `resort_reservation_system`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`customer` (
  `id` INT(11) NOT NULL,
  `last_name` VARCHAR(20) NULL DEFAULT NULL,
  `first_name` VARCHAR(20) NULL DEFAULT NULL,
  `middle_name` VARCHAR(20) NULL DEFAULT NULL,
  `contact_number` VARCHAR(15) NULL DEFAULT NULL,
  `address` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`employee` (
  `id` INT(11) NOT NULL,
  `last_name` VARCHAR(20) NULL DEFAULT NULL,
  `first_name` VARCHAR(20) NULL DEFAULT NULL,
  `middle_name` VARCHAR(20) NULL DEFAULT NULL,
  `contact_number` VARCHAR(15) NULL DEFAULT NULL,
  `address` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `hired_date` DATE NULL DEFAULT NULL,
  `rate` VARCHAR(20) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `department` VARCHAR(50) NULL DEFAULT NULL,
  `position` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`billingstatement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`billingstatement` (
  `id` INT(11) NOT NULL,
  `mode_of_payment` VARCHAR(20) NULL DEFAULT NULL,
  `amount` DECIMAL(2,0) NULL DEFAULT NULL,
  `date_of_payment` DATE NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `employee_id` INT(11) NOT NULL,
  `customer_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_billing statement_employee1_idx` (`employee_id` ASC),
  INDEX `fk_billing statement_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_billing statement_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `resort_reservation_system`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_billing statement_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `resort_reservation_system`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_billing statement_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `resort_reservation_system`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_billing statement_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `resort_reservation_system`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `check_in` DATE NULL,
  `check_out` DATE NULL,
  `type_of_room` VARCHAR(10) NULL,
  `adults` VARCHAR(50) NULL,
  `kids` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_billingstatement1_idx` ( ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_has_room_reservation1_idx` ( ASC),
  INDEX `fk_reservation_has_room_room1_idx` ( ASC),
  CONSTRAINT `fk_reservation_billingstatement1`
    FOREIGN KEY ()
    REFERENCES `resort_reservation_system`.`billingstatement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_billingstatement1`
    FOREIGN KEY ()
    REFERENCES `resort_reservation_system`.`billingstatement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`customer_has_reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`customer_has_reservation` (
  `id` INT(11) NOT NULL,
  `date_of_arrival` DATE NULL DEFAULT NULL,
  `date_of_departure` DATE NULL DEFAULT NULL,
  `desired_room_type` VARCHAR(20) NULL DEFAULT NULL,
  `requests` VARCHAR(50) NULL DEFAULT NULL,
  `reservation_id` INT(11) NOT NULL,
  `customer_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_has_reservation_reservation1_idx` (`reservation_id` ASC),
  INDEX `fk_customer_has_reservation_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_customer_has_reservation_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `resort_reservation_system`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_has_reservation_reservation1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `resort_reservation_system`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_has_reservation_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `resort_reservation_system`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_has_reservation_reservation1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `resort_reservation_system`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`employee_assist_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`employee_assist_customer` (
  `id` INT(11) NOT NULL,
  `customer_id` INT(11) NOT NULL,
  `employee_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_assist_customer_customer1_idx` (`customer_id` ASC),
  INDEX `fk_employee_assist_customer_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_employee_assist_customer_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `resort_reservation_system`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_assist_customer_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `resort_reservation_system`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_assist_customer_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `resort_reservation_system`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_assist_customer_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `resort_reservation_system`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`room` (
  `id` INT(11) NOT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `rate` VARCHAR(20) NULL DEFAULT NULL,
  `capacity` INT(11) NULL DEFAULT NULL,
  `availability` VARCHAR(45) NULL DEFAULT NULL,
  `billingStatement_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_room_billing statement1_idx` (`billingStatement_id` ASC),
  CONSTRAINT `fk_room_billing statement1`
    FOREIGN KEY (`billingStatement_id`)
    REFERENCES `resort_reservation_system`.`billingstatement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`reservation_has_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`reservation_has_room` (
  `id` INT(11) NOT NULL,
  `reservation_start_date` DATE NULL DEFAULT NULL,
  `reservation_end_date` DATE NULL DEFAULT NULL,
  `reservation_id` INT(11) NOT NULL,
  `room_id` INT(11) NOT NULL,
  INDEX `fk_reservation_has_room_reservation1` (`reservation_id` ASC),
  INDEX `fk_reservation_has_room_room1` (`room_id` ASC),
  CONSTRAINT `fk_reservation_has_room_reservation1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `resort_reservation_system`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_has_room_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `resort_reservation_system`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_has_room_reservation1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `resort_reservation_system`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_has_room_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `resort_reservation_system`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`service` (
  `id` INT(11) NOT NULL,
  `service_availed` VARCHAR(30) NULL DEFAULT NULL,
  `cost` VARCHAR(45) NULL DEFAULT NULL,
  `employee_id` INT(11) NOT NULL,
  `customer_id` INT(11) NOT NULL,
  `billingStatement_id` INT(11) NOT NULL,
  `room_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_service_employee1_idx` (`employee_id` ASC),
  INDEX `fk_service_customer1_idx` (`customer_id` ASC),
  INDEX `fk_service_billing statement1_idx` (`billingStatement_id` ASC),
  INDEX `fk_service_room1_idx` (`room_id` ASC),
  CONSTRAINT `fk_service_billing statement1`
    FOREIGN KEY (`billingStatement_id`)
    REFERENCES `resort_reservation_system`.`billingstatement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `resort_reservation_system`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `resort_reservation_system`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `resort_reservation_system`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `resort_reservation_system`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resort_reservation_system`.`user` (
  `id` INT(11) NOT NULL,
  `first_name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `last_name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `username` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `auth_key` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL,
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `password_reset_token` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `status` SMALLINT(6) NOT NULL DEFAULT '10',
  `created_at` INT(11) NOT NULL,
  `updated_at` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `password_reset_token` (`password_reset_token` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
